# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x2S_WTfwYVrnXA3LTe9NZUFRymKIO3Va
"""

def swap(x, y):
    """
    Task 1
    - Create a function that would swap the value of x and y using only x and y as variables.
    - x and y must be numeric.
    - Return -1 if x and y is not numeric, and
    - print the swapped values if both x and y are numeric.
    """
    if not (isinstance(x, (int, float)) and isinstance(y, (int, float))):
        return -1
    x, y = y, x
    print("Swapped values:", x, y)
    return x, y


# Task 2: Run test cases
print("Result 1:", swap("Apple", 10))   # Should return -1
print("Result 2:", swap(9, 17))         # Should print: Swapped values: 17 9