# -*- coding: utf-8 -*-
"""Farida NTU entrance

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x2S_WTfwYVrnXA3LTe9NZUFRymKIO3Va
"""

def swap(x, y):
    """
    Task 1
    - Create a function that would swap the value of x and y using only x and y as variables.
    - x and y must be numeric.
    - Return -1 if x and y is not numeric, and
    - print the swapped values if both x and y are numeric.
    """
    if not (isinstance(x, (int, float)) and isinstance(y, (int, float))):
        return -1
    x, y = y, x
    print("Swapped values:", x, y)
    return x, y


# Task 2: Run test cases
print("Result 1:", swap("Apple", 10))   # Should return -1
print("Result 2:", swap(9, 17))         # Should print: Swapped values: 17 9

def find_and_replace(lst, find_val, replace_val):
    """
    Task 1
    - Create a function that searches for all occurrences of a value (find_val) in a given list (lst)
      and replaces them with another value (replace_val).
    - lst must be a list.
    - Return the modified list.
    """
    if not isinstance(lst, list):
        return "Invalid input"

    result = [replace_val if item == find_val else item for item in lst]
    return result


# Task 2: Run test cases
print("Test 1:", find_and_replace([1, 2, 3, 4, 2, 2], 2, 5))
print("Test 2:", find_and_replace(["apple", "banana", "apple"], "apple", "orange"))

def update_dictionary(d):
    """
    Task 1:
    - Add a new key-value pair
    - Modify the value of an existing key
    - Delete a specific key
    - Return the updated dictionary
    """
    if not isinstance(d, dict):
        return "Invalid input"

    # Add new key-value pair
    d["new_key"] = "new_value"

    # Modify existing key (if it exists)
    if "name" in d:
        d["name"] = "Updated Name"

    # Delete specific key (if it exists)
    if "age" in d:
        del d["age"]

    return d


# Task 2: Test case
sample_dict = {
    "name": "Farida",
    "age": 47,
    "city": "Singapore"
}

result = update_dictionary(sample_dict)
print("Updated dictionary:", result)